batch_size: 120
val_batch_size: 100
epochs: 100
base_dir: "data/Hippocampus/"
save_dir: "save/simclr/Hippocampus"
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 10
weight_decay: 10e-6
fp16_precision: False
img_size: 64
model:
  out_dim: 256
  embed_dim: 512
  base_model: "resnet18"

dataset:
  s: 1
  input_shape: (112,112,3)
  num_workers: 0
  valid_size: 0.01

loss:
  temperature: 0.5
  use_cosine_similarity: True
#  beta: 0.1  # use 0.1 0.3 0.5 0.7 0.9  have used 0.1 0.3 nobeta
#  stratedgy: 1  #  choose the hard positive
#  estimator: "hard"
#  tau_plus: 0.1
